---
- hosts: all
  tasks:
    - name: Install Apache
      yum: 
        name: "{{ item }}"
        state: present
        with_items:
          - httpd
          - httpd-tools
    - name: Ensure apache started
      service:
        name: httpd
        state: started
        enabled: yes
 
