---
- hosts: all
  become: true
  tasks:
    - name: Install Apache
      yum: 
        name: "{{ packages }}"
      vars:
        packages:
        - httpd
        - httpd-tools  
    - name: Ensure apache started
      service:
        name: httpd
        state: started
        enabled: yes
 
