---
- name: Create a new file
  hosts: all
  become: true
  tasks:
    - name: Create a file in /tmp
      file:
        src: /tmp/rekha.template
        dest: /tmp/template2
        owner: lnxcfg
        group: lnxcfg
        mode: 0755
        state: hard 
